# Generated by Django 4.1.3 on 2022-12-06 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jio_calci', '0002_rename_category_category1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Instances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.IntegerField(blank=100, max_length=100, null=True)),
                ('skuname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jio_calci.skuname1')),
            ],
        ),
    ]
