# Generated by Django 4.1.3 on 2022-12-06 07:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jio_calci', '0003_instances'),
    ]

    operations = [
        migrations.CreateModel(
            name='fixedrate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.FloatField(blank=100, max_length=1.0, null=True)),
                ('skuname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='jio_calci.skuname1')),
            ],
        ),
        migrations.DeleteModel(
            name='Instances',
        ),
    ]
